### PR TITLE
Use default Yarn cache folder

### PR DESCRIPTION
**Pull request by stevenharman**
Yarn has a whole set of "[preferred cache directories](https://github.com/yarnpkg/yarn/blob/e70c067dff8138a4ce865f5bcea091005cb1d83a/src/constants.js#L55-L71)", and on the typical Linux-based OS, the first preference is going to be `~/.cache/yarn`. We could just change the cache save path to that, but it's probably better to explicitly call out the cache directory we're using.

### CODE REVIEW

**Comment by zzak** [comment]
@stevenharman Would you mind rebasing? :bow:

**Comment by stevenharman** [comment]
@zzak done. 😁

**Comment by ryanwohara** [comment]
LGTM

**Comment by zzak** [comment]
Thanks! :bow:

**Comment by zzak** [comment]
@stevenharman Does it matter if `~/.cache` doesn't already exist? Although it does on my system, just curious.

**Comment by stevenharman** [comment]
From what I've seen, Yarn will create the cache directory if it doesn't exist. So we should be GTG. 👍

**Pull request merged**
