### PR TITLE
 feat: Add rubocop for project.

### PR DESCRIPTION
**Pull request by lanzhiheng**

### CODE REVIEW

**Comment by lanzhiheng** [comment]
Hello @KyleTryon @gmemstr for better testing the Rubocop function in [ruby-orb](https://github.com/CircleCI-Public/ruby-orb/pull/44#issuecomment-662934571), I think we can integrate Rubocop in this project. Can you consider to accept this PR?

**Comment by gmemstr** [comment]
@lanzhiheng Would you mind adding the command to initiate rubocop commands to the `.circleci/config.yml` file under the "test" job? That way we can validate they work properly for the project, then update it to use the orb's own command :)

**Comment by gmemstr** [comment]
Thank you! 😄

**Comment by lanzhiheng** [comment]
@gmemstr updated. I will change to orb's own command after you publish the new version of orb.  :)

**Review by nbialostosky — COMMENTED** [review]
Thanks for taking the time to make this update, it looks like it covers everything and the command works within the build.

**Review by gmemstr — APPROVED** [review]

**Pull request merged**
